import os
import anthropic
import base64
import json
import re

diversity_number = 3
all_api_keys = [
    'From File'
]

PROMPT_7 = '''
Imagine you are a human annotator, tasked with generating a Visual Question Answering benchmark dataset for CIRCULAR documents. You need to cover each and every part of the document and generate as many question answer pairs as possible. The question's answers should be obtained from the document itself, directly, that is, EXTRACTIVE type questions. And they should span the ENTIRE DOCUMENT, no part should be left out. GENERATE ATLEAST 30 Questions per document.
The output should be in this Format:
Here are 30 question-answer pairs based on the information provided in the image:
1. <Question> : <Answer>
2. <Question> : <Answer>
.....
30. <Question> : <Answer>
'''

PROMPT_filter = '''
Given below are 4 sets of Question and Answer pairs given by you for a document. 4 sets of question answer pairs are generated by prompting the same document with the same prompt. Question and answers in each set could be different from the other set. Give me a set of 40 UNIQUE question-answer pairs from all the 4 sets based on the context of the question-answer pair.
The input is in the format
<QNO>. <pair['question']> : <pair['answer']>\n.
Here QNO is the question number. pair['question'] is the question and pair['answer'] is the answer.
Give me UNIQUE question-answer pairs in the below json format.
Here is a set of 40 unique question-answer pairs based on the context provided:
{
 [
 {'id':1,
 'question:<QUESTION>',
 'answer':<ANSWER>
 },
 {'id':2,
 'question:<QUESTION>',
 'answer':<ANSWER>
 },
 ....
 {'id':40,
 'question:<QUESTION>',
 'answer':<ANSWER>
 }
 ]
}
'''